apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-microservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-microservice
  template:
    metadata:
      labels:
        app: my-microservice
    spec:
      containers:
        - name: api
          image: 226188248944.dkr.ecr.ca-central-1.amazonaws.com/microservice-to-millions-artifacts-ecr:v1
          ports:
            - containerPort: 5050
          readinessProbe:
            httpGet:
              path: /
              port: 5050
            initialDelaySeconds: 5
          resources:
            requests:
              cpu: 100m
              memory: 128Mi